/**
 * The Lucide icons this app actually renders.
 *
 * Importing lucide's whole `icons` barrel pulls in every icon in the set
 * (~400 kB before gzip), so each icon is imported by name instead and collected
 * into the object `createIcons()` looks up.
 *
 * Keys must be the PascalCase form of the `data-lucide` attribute value —
 * that is what Lucide resolves against. Adding a new `data-lucide="foo-bar"`
 * anywhere means adding `FooBar` here, otherwise the icon silently renders
 * nothing and Lucide logs a warning.
 */

import {
  AlertCircle,
  AlertTriangle,
  Calendar,
  CalendarCheck,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  Clock,
  Cloud,
  Coins,
  Copy,
  Download,
  Eye,
  FileDown,
  FileSpreadsheet,
  Flame,
  Inbox,
  Info,
  Key,
  KeyRound,
  LayoutDashboard,
  Link,
  ListChecks,
  ListFilter,
  Lock,
  LockKeyhole,
  LogIn,
  LogOut,
  Moon,
  Package,
  PackageCheck,
  Phone,
  PlusCircle,
  RefreshCw,
  Save,
  Search,
  SearchX,
  Send,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sun,
  Trash2,
  User,
  Wallet,
} from 'lucide';

export const appIcons = {
  AlertCircle,
  AlertTriangle,
  Calendar,
  CalendarCheck,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  Clock,
  Cloud,
  Coins,
  Copy,
  Download,
  Eye,
  FileDown,
  FileSpreadsheet,
  Flame,
  Inbox,
  Info,
  Key,
  KeyRound,
  LayoutDashboard,
  Link,
  ListChecks,
  ListFilter,
  Lock,
  LockKeyhole,
  LogIn,
  LogOut,
  Moon,
  Package,
  PackageCheck,
  Phone,
  PlusCircle,
  RefreshCw,
  Save,
  Search,
  SearchX,
  Send,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sun,
  Trash2,
  User,
  Wallet,
};
